# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'ready to ship', url: 'ready-ship'}
- {name: 'on demand', url: 'on-demand'}
- {name: 'shop FAQ', url: 'shop'}
- {name: 'reference', url: 'reference'}
- {name: 'about', url: 'about'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'circle-o', link: 'https://www.ravelry.com/people/inherentlee', mouseover: 'inherentlee on ravelry (basically yarn facebook)'}
- {icon: 'github', link: 'https://github.com/lee0c', mouseover: 'lee0c on github'}
- {icon: 'code-fork', link: 'https://github.com/lee0c.github.io', mouseover: 'website source'}
- {icon: 'envelope', link: 'mailto:lee.cattarin@gmail.com', mouseover: 'email me'}
- {icon: 'twitter', link: 'https://twitter.com/inherentlee', mouseover: 'inherentlee on twitter'}
- {icon: 'instagram', link: 'instagram', mouseover: 'inherentlee on instagram'}
# - {icon: 'rss-square', link: 'feed.xml'}

# Customize site text
pagination:
  next_page: 'next >'
  previous_page: '< prev'

# sharing_button_prompt: 'Feel free to share!'

related_posts: 'related:'

post_date_prefix: 'last updated'
