# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'ready to ship', url: 'ready-to-ship'}
- {name: 'on demand', url: 'on-demand'}
- {name: 'shop FAQ', url: 'shop'}
- {name: 'gallery', url: 'gallery'}
- {name: 'reference', url: 'reference'}
- {name: 'about', url: 'about'}
- {name: 'contact me', url: 'contact'}

post_date_prefix: 'posted on'
