# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'project gallery', url: 'gallery'}
- {name: 'ready to ship', url: 'ready-to-ship'}
- {name: 'on demand', url: 'on-demand'}
- {name: 'shop FAQ', url: 'shop'}
- {name: 'reference', url: 'reference'}
- {name: 'about', url: 'about'}
- {name: 'contact me', url: 'contact'}

# Customize site text
pagination:
  next_page: 'next >'
  previous_page: '< prev'

post_date_prefix: 'last updated'
