# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'gallery', url: 'gallery'}
- {name: 'reference', url: 'reference'}
- {name: 'about', url: 'about'}
- {name: 'contact/shops', url: 'contact'}

post_date_prefix: 'posted on'
